### PR TITLE
 [1.20.4] add support for AFTER_HEALTH_BAR event with colorful hearts

### PR DESCRIPTION
**Pull request by Terrails**
Same as #24

### CODE REVIEW

**Comment by TheDeathlyCow** [comment]
Hi. I'll review these better when I have time (realistically not until the end of next week). But I can say that support for Colourful Hearts was removed from Thermoo 1.20.2+ *by default* and was moved into Thermoo Patches (along with a bunch of other mods). So, this PR is probably going to be closed.

**Comment by Terrails** [comment]
Ah okay. I'll close both PRs for 1.20.2+ then and move them over to Thermoo Patches.

**Comment by TheDeathlyCow** [comment]
Thanks. Also thanks for handling these updates, not sure why people are reporting issues with my mod to you, that seems wrong to me.

**Comment by Terrails** [comment]
> Thanks. Also thanks for handling these updates, not sure why people are reporting issues with my mod to you, that seems wrong to me.

No worries, I just did a bunch of refactoring to make my life easier when adding compatibility with custom hearts from other mods and the side effect is that I had to change a lot of things internally. But it is a fact that things broke by me making a breaking change, so I might as well fix it since its really simple.

**Pull request closed without merging**
